# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.17.2
loom_version=1.11-SNAPSHOT
fabric_version=0.116.5+1.21.1
fabric_kotlin_version=1.13.4+kotlin.2.2.0

# Dependencies
bettercombat_version=2.2.4+1.21.1
clothconfig_version=15.0.140

# Mod Properties
mod_version=0.43.7+1.21.1
maven_group=org.wdfeer.infinity_hoe
archives_base_name=infinity_hoe
