# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.4
loom_version=1.15-SNAPSHOT
fabric_kotlin_version=1.13.9+kotlin.2.3.10

# Depends
fabric_api_version=0.141.3+1.21.11
bettercombat_version=3.0.1+1.21.11
clothconfig_version=21.11.153
tinyconfig_version=3.1.0

# Infinity Hoe
mod_version=0.43.6+1.21.11
maven_group=org.wdfeer.infinity_hoe
archives_base_name=infinity_hoe
